### ISSUE TITLE
NameError (uninitialized constant Issue::FullTextSearch::Mroonga::FtsIssue)

### ISSUE THREAD

**Issue by sho-suzuki** [okkez/redmine_full_text_search#20]
お世話になっております。
下記の環境でplugin migrate、redmineのリブートは正常に終了するのですが、
検索ボックスにワードを入れて検索しようとすると500 internal errorとなります。

```bash:redmine環境
Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  full_text_search               0.3.0
  redmine_backlogs               v1.0.6
```

production.log

```bash
Started GET "/search?utf8=%E2%9C%93&q=mroonga" for 127.0.0.1 at 2017-04-04 00:41:02 +0900
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"磬\~S", "q"=>"mroonga"}
  Current user: sho.suzuki (id=7)
Completed 500 Internal Server Error in 65ms (ActiveRecord: 10.1ms)

NameError (uninitialized constant Issue::FullTextSearch::Mroonga::FtsIssue):
  plugins/redmine_full_text_search/lib/full_text_search/mroonga.rb:51:in `fetch_ranks_and_ids'
  plugins/redmine_full_text_search/lib/full_text_search/mroonga.rb:119:in `search_result_ranks_and_ids'
  plugins/redmine_full_text_search/lib/full_text_search/fetcher.rb:24:in `block in load_result_ids'
  plugins/redmine_full_text_search/lib/full_text_search/fetcher.rb:22:in `each'
  plugins/redmine_full_text_search/lib/full_text_search/fetcher.rb:22:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  app/controllers/search_controller.rb:75:in `index'
  plugins/redmine_full_text_search/lib/full_text_search/hooks/controller_search_index.rb:9:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

logを見るに

- Parameters: {"utf8"=>"磬\~S", "q"=>"mroonga"} のutf8のvalueがおかしい
- Issue::FullTextSearch::Mroonga::FtsIssueが初期化されていない

ように見えます。対処方法についてご教授願えますでしょうか。

**Comment by okkez** [comment]
インストール方法がおかしい気がします。
ログに出ているパスがおかしいです。

`plugins/redmine_full_text_search/lib/full_text_search/mroonga.rb`

ではなく

`plugins/full_text_search/lib/full_text_search/mroonga.rb`

となるはずです。
正しくインストールできていない気がするので README の手順通りにインストールできているかどうか確認してください。

**Comment by sho-suzuki** [comment]
早速の回答ありがとうございました！
他のプラグインだと頭に"redmine_"がついてたので、合わせてつけたのが原因でした。
外したところDBmigrationが走り、検索窓で検索することが出来ました。ご対応ありがとうございました。

**Comment by okkez** [comment]
解決できてよかったです！
