### ISSUE TITLE
Duplicate entry error when creating searcher_records for custom value

### ISSUE THREAD

**Issue by iquiw** [okkez/redmine_full_text_search#36]
When migrating Full Text Search, I got the following error.

```
-- execute("    INSERT INTO searcher_records(original_id, original_type, project_id, original_created_on, original_updated_on, comments)\n    SELECT base.id, 'Changeset', project_id, base.committed_on, NULL, base.comments FROM changesets AS base\n JOIN repositories AS r ON (base.repository_id = r.id);")rake aborted!
StandardError: An error has occurred, all later migrations canceled:
Mysql2::Error: Duplicate entry '3303-CustomValue' for key 'index_searcher_records_unique':     INSERT INTO searcher_records(original_id, original_type, project_id, status_id, is_private, original_created_on, original_updated_on, value, custom_field_id)
    SELECT base.id, 'CustomValue', r.project_id, status_id, is_private, NULL, NULL, base.value, base.custom_field_id FROM custom_values AS base
     JOIN issues AS i ON (base.customized_id = i.id)
    JOIN custom_fields AS f ON (base.custom_field_id = f.id)
    JOIN custom_fields_projects AS r ON (base.custom_field_id = r.custom_field_id)
 WHERE searchable = true;
/usr/local/bundle/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `_query'
/usr/local/bundle/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `block in query'
/usr/local/bundle/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `query'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/usr/src/redmine/plugins/full_text_search/db/migrate/20170630063657_create_searcher_records.rb:219:in `load_custom_values'
```

The table contents are like this.

```
mysql> SELECT base.id, 'CustomValue', r.project_id, status_id, is_private, NULL, NULL, base.value, base.custom_field_id FROM custom_values AS base JOIN issues AS i ON (base.customized_id = i.id) JOIN custom_fields AS f ON (base.custom_field_id = f.id) JOIN custom_fields_projects AS r ON (base.custom_field_id = r.custom_field_id) WHERE searchable = true;
+------+-------------+------------+-----------+------------+------+------+-------+-----------------+
| id   | CustomValue | project_id | status_id | is_private | NULL | NULL | value | custom_field_id |
+------+-------------+------------+-----------+------------+------+------+-------+-----------------+
| 3303 | CustomValue |         16 |        14 |          0 | NULL | NULL | XXXX  |               5 |
| 3303 | CustomValue |         81 |        14 |          0 | NULL | NULL | XXXX  |               5 |
| 3303 | CustomValue |         89 |        14 |          0 | NULL | NULL | XXXX  |               5 |
| 3303 | CustomValue |         90 |        14 |          0 | NULL | NULL | XXXX  |               5 |
| 3303 | CustomValue |         92 |        14 |          0 | NULL | NULL | XXXX  |               5 |
```

**Comment by okkez** [comment]
Could you try this patch?

```diff
diff --git a/db/migrate/20170630063657_create_searcher_records.rb b/db/migrate/20170630063657_create_searcher_records.rb
index 4a8ed49..ce47d3b 100644
--- a/db/migrate/20170630063657_create_searcher_records.rb
+++ b/db/migrate/20170630063657_create_searcher_records.rb
@@ -213,7 +213,7 @@ class CreateSearcherRecords < ActiveRecord::Migration
     sql_rest = <<-SQL
     JOIN issues AS i ON (base.customized_id = i.id)
     JOIN custom_fields AS f ON (base.custom_field_id = f.id)
-    JOIN custom_fields_projects AS r ON (base.custom_field_id = r.custom_field_id)
+    JOIN custom_fields_projects AS r ON (base.custom_field_id = r.custom_field_id AND r.project_id = i.project_id)
     SQL
     sql = "#{sql_base} #{sql_rest} WHERE searchable = true;"
     execute(sql)
@@ -225,7 +225,6 @@ class CreateSearcherRecords < ActiveRecord::Migration
     sql_rest = <<-SQL
     JOIN projects AS p ON (base.customized_id = p.id)
     JOIN custom_fields AS f ON (base.custom_field_id = f.id)
-    JOIN custom_fields_projects AS r ON (base.custom_field_id = r.custom_field_id)
     SQL
     sql = "#{sql_base} #{sql_rest} WHERE searchable = true;"
     execute(sql)
```

**Comment by iquiw** [comment]
@okkez Thank you for quick reply.

Is the 2nd chunk of the diff correct? I got `Unknown column 'r.project_id' in 'field list':` error.
Should it be similar to the 1st chunk?

**Comment by okkez** [comment]
How about this?

We don't need to join `custom_fields_projects` when handle projects' `custom_values`. But we need project_id here.

```diff
diff --git a/db/migrate/20170630063657_create_searcher_records.rb b/db/migrate/20170630063657_create_searcher_records.rb
index 4a8ed49..2a5386f 100644
--- a/db/migrate/20170630063657_create_searcher_records.rb
+++ b/db/migrate/20170630063657_create_searcher_records.rb
@@ -213,19 +213,18 @@ class CreateSearcherRecords < ActiveRecord::Migration
     sql_rest = <<-SQL
     JOIN issues AS i ON (base.customized_id = i.id)
     JOIN custom_fields AS f ON (base.custom_field_id = f.id)
-    JOIN custom_fields_projects AS r ON (base.custom_field_id = r.custom_field_id)
+    JOIN custom_fields_projects AS r ON (base.custom_field_id = r.custom_field_id AND r.project_id = i.project_id)
     SQL
     sql = "#{sql_base} #{sql_rest} WHERE searchable = true;"
     execute(sql)
 
     sql_base = <<-SQL
     INSERT INTO searcher_records(original_id, original_type, project_id, original_created_on, original_updated_on, #{columns.join(", ")})
-    SELECT base.id, '#{table.classify}', r.project_id, #{transform(original_columns)} FROM #{table} AS base
+    SELECT base.id, '#{table.classify}', p.id, #{transform(original_columns)} FROM #{table} AS base
     SQL
     sql_rest = <<-SQL
     JOIN projects AS p ON (base.customized_id = p.id)
     JOIN custom_fields AS f ON (base.custom_field_id = f.id)
-    JOIN custom_fields_projects AS r ON (base.custom_field_id = r.custom_field_id)
     SQL
     sql = "#{sql_base} #{sql_rest} WHERE searchable = true;"
     execute(sql)
```

**Comment by iquiw** [comment]
With the patch, the migration process was finished without error.

However, I got ``undefined method `display_score?'`` error when trying to open issue page.
I will check it and file new issue if necessary.

Thanks.

**Comment by okkez** [comment]
Thank you for confirmation.

**Comment by iquiw** [comment]
For the record, it turns out  ``undefined method `display_score?'`` happened when using both Full text search  and [redmine_persist_wfmt](https://github.com/pinzolo/redmine_persist_wfmt).

So it might not be problem of Full text search, although I don't know how the problem happens.

**Comment by okkez** [comment]
Thank you for reporting. I will investigate the issue later.

**Comment by okkez** [comment]
@iquiw I've tried to install redmine\_persist\_wfmt. But it does not support recent Redmine, I think.

**Comment by iquiw** [comment]
@okkez I see. Thank you for trying!

Unfortunately, the plugin is required for my use case.
I will try to find workaround or consider to give it up.
